//! CCH weights format - customized edge weights for CCH
//!
//! Stores per-mode edge weights for both UP and DOWN edges.
//! Generated by Step 8 (customization).
//!
//! # Zero-Copy Reads (#147, #296)
//!
//! For Belgium-scale data, four modes × {time, dist} weights total
//! ~6 GB on disk. Eagerly copying these into `Vec<u32>` doubles the
//! resident memory of an mmap-backed server (mmap pages + Vec heap).
//! The fields are `ArcCow<u32>` so they can hold either an owned
//! `Vec<u32>` (legacy / writer / construction sites) or a zero-copy
//! view into a memory-mapped container section, with the `Arc<Mmap>`
//! clone keeping the mapping live for the lifetime of the struct.
//!
//! # Eviction interaction (#149 / #296)
//!
//! After boot, the server hints `madvise(MADV_DONTNEED)` on the
//! `cch_weights.up`/`.down` byte ranges because the routing hot path
//! reads through pre-built flat adjacencies, not these arrays. The
//! `ArcCow::Mmap` variant holds the same `Arc<Mmap>` that owns the
//! pages — dropping a `CchWeights` decrements that strong count, and
//! once all clones drop, `munmap` runs and the kernel reclaims the
//! pages. The madvise hint stays valid until then; subsequent rare
//! reads (validators, transit fingerprint hash, recustomizers) page
//! the bytes back in at standard fault cost.

use anyhow::Result;
use std::fs::File;
use std::io::{BufReader, Read};
use std::path::Path;
use std::sync::Arc;

use super::crc;
use super::mmap::ArcCow;

const MAGIC: u32 = 0x43434857; // "CCHW"
const HEADER_LEN: usize = 32;
const FOOTER_LEN: usize = 16;
/// Current on-disk version. v3 (#306 PR 2) carries a per-direction
/// `width_flags` byte in header byte 7 that lets the body be encoded
/// as `[u16]` or `[u32]` independently for UP/DOWN edges. v2 stored
/// body in seconds (time weights) or meters (distance weights) at
/// fixed u32; v3 readers still accept v2 (width = u32 implied). v1
/// stored deciseconds / millimeters and is rejected — re-run step 8
/// to regenerate.
const VERSION: u16 = 3;
const VERSION_V2: u16 = 2;

/// Width flags packed into header byte 7 (v3+):
/// - bit 0: up body width  (0 = u32, 1 = u16)
/// - bit 1: down body width (0 = u32, 1 = u16)
const UP_COMPACT_FLAG: u8 = 0x01;
const DOWN_COMPACT_FLAG: u8 = 0x02;

/// Per-direction body width for a CCH weights file (#306 PR 2).
///
/// At write time, step 8 picks `U16` when the direction's max value
/// fits losslessly in `u16` (≤ 65 535). On Belgium that's car and
/// bike for time weights; foot stays `U32` until PR 3's u24+overflow
/// table lands.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WeightWidth {
    U16,
    U32,
}

impl WeightWidth {
    #[inline]
    pub fn bytes_per_entry(self) -> usize {
        match self {
            Self::U16 => 2,
            Self::U32 => 4,
        }
    }

    /// Number of bytes occupied by a body of `n` entries at this width,
    /// padded up to the next 4-byte boundary so the following `u32`
    /// arrays (middles) stay aligned for `bytemuck::cast_slice`.
    #[inline]
    pub fn padded_body_bytes(self, n: usize) -> usize {
        let raw = self.bytes_per_entry() * n;
        (raw + 3) & !3
    }

    /// `WeightWidth::U16` iff every value in `weights` fits in `u16`.
    /// `u32::MAX` (the "no edge" sentinel) maps to `u16::MAX` on the
    /// compact path — that round-trip is lossless, so the sentinel
    /// itself doesn't force U32.
    #[inline]
    pub fn choose(weights: &[u32]) -> Self {
        if weights
            .iter()
            .all(|&w| w == u32::MAX || w <= u16::MAX as u32)
        {
            Self::U16
        } else {
            Self::U32
        }
    }
}

/// Per-direction weight array — either compact u16 or wide u32.
///
/// The hot routing path doesn't read [`CchWeights`] directly (see
/// codex review on #279); access is through pre-built
/// `UpAdjFlat` / `DownReverseAdjFlat` that embed the weights inline.
/// CchWeights stays resident in `ModeData` mainly for unpack, validators,
/// and recustomization, so the storage backing matters for steady-state
/// RSS but not for routing latency.
///
/// Mmap-backed variants borrow from the live `Arc<Mmap>` covering the
/// container; widening to `u32` happens on read via [`Self::get`].
/// After madvise(DONTNEED) on the container section, the mmap pages
/// are evictable — only the small enum wrapper stays on the heap.
#[derive(Debug, Clone)]
pub enum WeightArray {
    /// Compact `u16` storage. Reader uses `u16::MAX` as the
    /// "no edge" sentinel (same role as `u32::MAX` in the U32 variant
    /// — by convention this is widened back to `u32::MAX` by `get`).
    U16(ArcCow<u16>),
    /// Native `u32` storage. Used when the direction's max value
    /// doesn't fit in `u16` (foot mode on Belgium, all distance
    /// arrays until PR 3 lands the u24 codec).
    U32(ArcCow<u32>),
}

impl WeightArray {
    /// Read entry `i`, widening to `u32`. The `u16::MAX` sentinel in
    /// the compact variant maps back to `u32::MAX` so the
    /// "no edge" semantic survives a round-trip.
    #[inline]
    pub fn get(&self, i: usize) -> u32 {
        match self {
            Self::U16(arr) => {
                let v = arr.as_slice()[i];
                if v == u16::MAX { u32::MAX } else { v as u32 }
            }
            Self::U32(arr) => arr.as_slice()[i],
        }
    }

    /// Length of the underlying array.
    #[inline]
    pub fn len(&self) -> usize {
        match self {
            Self::U16(arr) => arr.len(),
            Self::U32(arr) => arr.len(),
        }
    }

    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Iterate over the values widened to `u32`. The compact variant
    /// emits `u32::MAX` for entries equal to the `u16::MAX` sentinel.
    pub fn iter(&self) -> WeightArrayIter<'_> {
        WeightArrayIter {
            inner: self,
            i: 0,
            end: self.len(),
        }
    }

    /// Get the storage width — useful for size reporting and tests.
    #[inline]
    pub fn width(&self) -> WeightWidth {
        match self {
            Self::U16(_) => WeightWidth::U16,
            Self::U32(_) => WeightWidth::U32,
        }
    }

    /// Upgrade to an owned `Vec<u32>` for mutation. Used by callers
    /// that need to penalize or zero specific entries (e.g. exclude /
    /// avoid recustomization). The compact variant is widened in
    /// place; the wide variant produces a fresh Vec via `to_mut`.
    ///
    /// After calling this, the returned `&mut Vec<u32>` is the same
    /// storage `get`/`iter` will read. Subsequent reads decode
    /// through the U32 path.
    pub fn to_mut_vec(&mut self) -> &mut Vec<u32> {
        if let Self::U16(arr) = self {
            let widened: Vec<u32> = arr
                .as_slice()
                .iter()
                .map(|&v| if v == u16::MAX { u32::MAX } else { v as u32 })
                .collect();
            *self = Self::U32(ArcCow::from_vec(widened));
        }
        match self {
            Self::U32(arr) => match arr {
                ArcCow::Owned(v) => v,
                ArcCow::Mmap { .. } => {
                    // Mmap-backed → copy to owned so we can hand out
                    // a `&mut Vec`.
                    let owned: Vec<u32> = arr.as_slice().to_vec();
                    *arr = ArcCow::from_vec(owned);
                    if let ArcCow::Owned(v) = arr {
                        v
                    } else {
                        unreachable!("just set to ArcCow::Owned")
                    }
                }
            },
            Self::U16(_) => unreachable!("just upgraded to U32 above"),
        }
    }

    /// Construct from an owned `Vec<u32>` at the U32 width. Used by
    /// in-memory builders / writers that work in the wide space.
    #[inline]
    pub fn from_vec_u32(v: Vec<u32>) -> Self {
        Self::U32(ArcCow::from_vec(v))
    }

    /// Construct from an owned `Vec<u16>` at the U16 width.
    #[inline]
    pub fn from_vec_u16(v: Vec<u16>) -> Self {
        Self::U16(ArcCow::from_vec(v))
    }

    /// Empty array (U32 width).
    #[inline]
    pub fn empty() -> Self {
        Self::U32(ArcCow::from_vec(Vec::new()))
    }
}

impl From<Vec<u32>> for WeightArray {
    #[inline]
    fn from(v: Vec<u32>) -> Self {
        Self::U32(ArcCow::from_vec(v))
    }
}

/// Iterator over a [`WeightArray`], emitting `u32` values.
pub struct WeightArrayIter<'a> {
    inner: &'a WeightArray,
    i: usize,
    end: usize,
}

impl Iterator for WeightArrayIter<'_> {
    type Item = u32;
    #[inline]
    fn next(&mut self) -> Option<u32> {
        if self.i >= self.end {
            None
        } else {
            let v = self.inner.get(self.i);
            self.i += 1;
            Some(v)
        }
    }

    #[inline]
    fn size_hint(&self) -> (usize, Option<usize>) {
        let remaining = self.end - self.i;
        (remaining, Some(remaining))
    }
}

impl ExactSizeIterator for WeightArrayIter<'_> {}

/// CCH weights - stores weights and relaxed middle nodes for UP and DOWN edges.
/// The middle arrays are the post-triangle-relaxation middles — these are the
/// correct middles for path unpacking (the topology's middles are from contraction
/// and may be suboptimal).
///
/// `up` / `down` are [`WeightArray`] (u16 or u32, per direction).
/// `up_middle` / `down_middle` stay [`ArcCow<u32>`] — middle node ids
/// can address `n_nodes` which on a planet-scale CCH exceeds 65 535.
/// All reads go through `WeightArray::get` which widens transparently.
#[derive(Debug, Clone)]
pub struct CchWeights {
    pub up: WeightArray,
    pub down: WeightArray,
    /// Relaxed middle nodes for UP shortcuts (empty if not available — use topo middles)
    pub up_middle: ArcCow<u32>,
    /// Relaxed middle nodes for DOWN shortcuts (empty if not available — use topo middles)
    pub down_middle: ArcCow<u32>,
}

pub struct CchWeightsFile;

impl CchWeightsFile {
    pub fn read<P: AsRef<Path>>(path: P) -> Result<CchWeights> {
        let file = File::open(path.as_ref())?;
        let file_len = file.metadata()?.len() as usize;
        Self::read_from_reader(BufReader::new(file), file_len)
    }

    /// Read directly from an in-memory byte slice (e.g. an mmap-backed
    /// section of a `butterfly.dat` container). Allocating path —
    /// produces owning `ArcCow::Owned` Vecs.
    pub fn read_from_bytes(bytes: &[u8]) -> Result<CchWeights> {
        Self::read_from_reader(std::io::Cursor::new(bytes), bytes.len())
    }

    /// Legacy zero-copy reader retained for tests / tools that already
    /// hold a `'static [u8]` (typically leaked `Box<[u8]>` fixtures).
    /// Production now wires through [`Self::read_from_mmap_unverified`]
    /// instead so the `Arc<Mmap>` strong count actually drops when the
    /// `CchWeights` goes out of scope (#296). This reader copies the
    /// body into owned `Vec<u32>` slabs — there is no `&'static` view
    /// stored in the returned struct.
    ///
    /// CRC is verified before returning.
    pub fn read_from_bytes_zero_copy(bytes: &'static [u8]) -> Result<CchWeights> {
        Self::read_from_bytes_zero_copy_inner(bytes, true)
    }

    /// Same as [`Self::read_from_bytes_zero_copy`] but elides the
    /// internal CRC walk over the body bytes. Caller MUST guarantee
    /// the bytes have already been verified upstream (e.g. via
    /// [`crate::formats::lazy_verify::LazyContainer`]). Skipping the
    /// per-format CRC here avoids paging the body in twice on the
    /// container load path.
    pub fn read_from_bytes_zero_copy_unverified(bytes: &'static [u8]) -> Result<CchWeights> {
        Self::read_from_bytes_zero_copy_inner(bytes, false)
    }

    /// Production mmap-backed reader (#296). Each `ArcCow<u32>` sub-field
    /// holds a clone of the `Arc<Mmap>` covering this container, so when
    /// the returned `CchWeights` drops, every Arc clone drops with it.
    /// Once the strong count reaches 0, `Mmap::drop` calls `munmap` and
    /// the kernel reclaims the pages (the madvise(DONTNEED) hint applied
    /// at boot stays valid for the mapping's lifetime).
    ///
    /// `byte_offset` and `byte_len` describe the position and length of
    /// the section within the container, as recorded in the directory
    /// entry. CRC walking is the caller's responsibility (typically
    /// driven through the lazy CRC layer before this call).
    ///
    /// The container writer guarantees 8-byte section alignment; combined
    /// with the 32-byte header, the four u32 sub-arrays start at offsets
    /// that are 4-byte aligned, matching `align_of::<u32>() == 4`.
    pub fn read_from_mmap_unverified(
        mmap: Arc<memmap2::Mmap>,
        byte_offset: usize,
        byte_len: usize,
    ) -> Result<CchWeights> {
        anyhow::ensure!(
            byte_offset.saturating_add(byte_len) <= mmap.len(),
            "cch.weights section out of bounds: off={byte_offset} len={byte_len} mmap_len={}",
            mmap.len()
        );
        anyhow::ensure!(
            byte_len >= HEADER_LEN + FOOTER_LEN,
            "cch.weights section too short for header+footer: {byte_len} bytes",
        );

        let header = &mmap[byte_offset..byte_offset + HEADER_LEN];
        let CchWeightsHeader {
            n_up,
            n_down,
            up_width,
            down_width,
        } = parse_header(header)?;

        // Layout v3 (with optional middle arrays):
        //   header(32) | up(width_up·n_up [+0-2 pad]) | down(width_down·n_down [+0-2 pad])
        //              | [v3 middles: up_middle(4·n_up) | down_middle(4·n_down)]
        //              | footer(16)
        //
        // u16 bodies are padded up to a 4-byte boundary so the
        // following arrays (the other direction's body and the u32
        // middles) stay aligned for `bytemuck::cast_slice` /
        // `ArcCow::<u32>::from_mmap`.
        let up_bytes = up_width.padded_body_bytes(n_up);
        let down_bytes = down_width.padded_body_bytes(n_down);
        let body_no_middle = up_bytes
            .checked_add(down_bytes)
            .ok_or_else(|| anyhow::anyhow!("cch.weights body size overflow"))?;
        // Middle arrays (when present) stay at u32 — see CchWeights doc.
        let middle_bytes = 4usize
            .checked_mul(n_up)
            .and_then(|u| u.checked_add(4usize.checked_mul(n_down)?))
            .ok_or_else(|| anyhow::anyhow!("cch.weights middle size overflow"))?;
        let expected_no_middle_len = HEADER_LEN
            .checked_add(body_no_middle)
            .and_then(|n| n.checked_add(FOOTER_LEN))
            .ok_or_else(|| anyhow::anyhow!("cch.weights section size overflow"))?;
        let expected_with_middle_len = expected_no_middle_len
            .checked_add(middle_bytes)
            .ok_or_else(|| anyhow::anyhow!("cch.weights w/ middle size overflow"))?;
        let has_middles = match byte_len {
            n if n == expected_no_middle_len => false,
            n if n == expected_with_middle_len => true,
            n => anyhow::bail!(
                "Invalid cch.weights size: got {}, expected {} (no middles) or {} (with middles)",
                n,
                expected_no_middle_len,
                expected_with_middle_len
            ),
        };

        // Container-absolute byte offsets for each sub-array.
        let up_off = byte_offset + HEADER_LEN;
        let down_off = up_off + up_bytes;

        let up = match up_width {
            WeightWidth::U16 => {
                WeightArray::U16(ArcCow::<u16>::from_mmap(Arc::clone(&mmap), up_off, n_up)?)
            }
            WeightWidth::U32 => {
                WeightArray::U32(ArcCow::<u32>::from_mmap(Arc::clone(&mmap), up_off, n_up)?)
            }
        };
        let down = match down_width {
            WeightWidth::U16 => {
                WeightArray::U16(ArcCow::<u16>::from_mmap(Arc::clone(&mmap), down_off, n_down)?)
            }
            WeightWidth::U32 => {
                WeightArray::U32(ArcCow::<u32>::from_mmap(Arc::clone(&mmap), down_off, n_down)?)
            }
        };

        let (up_middle, down_middle) = if has_middles {
            let upm_off = down_off + down_bytes;
            let dnm_off = upm_off + 4 * n_up;
            let upm = ArcCow::<u32>::from_mmap(Arc::clone(&mmap), upm_off, n_up)?;
            // Final clone consumes the local `mmap` binding.
            let dnm = ArcCow::<u32>::from_mmap(mmap, dnm_off, n_down)?;
            (upm, dnm)
        } else {
            let _ = mmap;
            (ArcCow::from_vec(Vec::new()), ArcCow::from_vec(Vec::new()))
        };

        Ok(CchWeights {
            up,
            down,
            up_middle,
            down_middle,
        })
    }

    fn read_from_bytes_zero_copy_inner(bytes: &'static [u8], verify: bool) -> Result<CchWeights> {
        // ----- Header (32 bytes) -----
        anyhow::ensure!(
            bytes.len() >= HEADER_LEN + FOOTER_LEN,
            "cch.weights too short for header+footer: {} bytes",
            bytes.len()
        );
        anyhow::ensure!(
            (bytes.as_ptr() as usize).is_multiple_of(4),
            "cch.weights section must start 4-byte aligned (got addr 0x{:x})",
            bytes.as_ptr() as usize
        );
        let header = &bytes[..HEADER_LEN];
        let CchWeightsHeader {
            n_up,
            n_down,
            up_width,
            down_width,
        } = parse_header(header)?;

        // v3 layout (with optional middles, per-direction body width):
        //   header(32) | up(width_up·n_up [+0-2 pad]) | down(width_down·n_down [+0-2 pad])
        //              | [up_middle(4·n_up) | down_middle(4·n_down)]
        //              | footer(16)
        // u16 bodies pad up to 4-byte boundary — see `padded_body_bytes`.
        let up_bytes = up_width.padded_body_bytes(n_up);
        let down_bytes = down_width.padded_body_bytes(n_down);
        let no_middle_len = HEADER_LEN + up_bytes + down_bytes + FOOTER_LEN;
        let with_middle_len = no_middle_len + 4 * (n_up + n_down);
        let has_middles = match bytes.len() {
            n if n == no_middle_len => false,
            n if n == with_middle_len => true,
            n => anyhow::bail!(
                "Invalid cch.weights size: got {}, expected {} (no middles) or {} (with middles)",
                n,
                no_middle_len,
                with_middle_len
            ),
        };

        let up_off = HEADER_LEN;
        let up_end = up_off + up_bytes; // includes padding
        let down_off = up_end;
        let down_end = down_off + down_bytes;

        // Read only the actual data bytes (skip any 0-2 byte tail pad).
        let up_data = up_width.bytes_per_entry() * n_up;
        let down_data = down_width.bytes_per_entry() * n_down;
        let up_body = &bytes[up_off..up_off + up_data];
        let down_body = &bytes[down_off..down_off + down_data];
        let up_vec: Vec<u32> = match up_width {
            WeightWidth::U16 => decode_u16_to_u32_vec(up_body),
            WeightWidth::U32 => bytemuck::cast_slice::<u8, u32>(up_body).to_vec(),
        };
        let down_vec: Vec<u32> = match down_width {
            WeightWidth::U16 => decode_u16_to_u32_vec(down_body),
            WeightWidth::U32 => bytemuck::cast_slice::<u8, u32>(down_body).to_vec(),
        };

        let (up_middle, down_middle, body_end) = if has_middles {
            let upm_off = down_end;
            let upm_end = upm_off + 4 * n_up;
            let dnm_off = upm_end;
            let dnm_end = dnm_off + 4 * n_down;
            let upm: &[u32] = bytemuck::cast_slice(&bytes[upm_off..upm_end]);
            let dnm: &[u32] = bytemuck::cast_slice(&bytes[dnm_off..dnm_end]);
            (upm.to_vec(), dnm.to_vec(), dnm_end)
        } else {
            (Vec::new(), Vec::new(), down_end)
        };

        if verify {
            let body = &bytes[..body_end];
            let computed_crc = {
                let mut d = crc::Digest::new();
                d.update(body);
                d.finalize()
            };
            let footer = &bytes[body_end..body_end + FOOTER_LEN];
            let stored_crc = u64::from_le_bytes(footer[0..8].try_into().unwrap());
            anyhow::ensure!(
                computed_crc == stored_crc,
                "CRC64 mismatch in cch.weights: computed 0x{:016X}, stored 0x{:016X}",
                computed_crc,
                stored_crc
            );
        }

        // Test-fixture path now also widens u16→u32 if needed; production
        // load goes through `read_from_mmap_unverified`.
        Ok(CchWeights {
            up: WeightArray::from_vec_u32(up_vec),
            down: WeightArray::from_vec_u32(down_vec),
            up_middle: ArcCow::from_vec(up_middle),
            down_middle: ArcCow::from_vec(down_middle),
        })
    }

    fn read_from_reader<R: Read>(mut reader: R, file_len: usize) -> Result<CchWeights> {
        let mut crc_digest = crc::Digest::new();

        let mut header = [0u8; HEADER_LEN];
        reader.read_exact(&mut header)?;
        crc_digest.update(&header);
        let CchWeightsHeader {
            n_up,
            n_down,
            up_width,
            down_width,
        } = parse_header(&header)?;

        // Read up weights body (padded to next 4-byte boundary).
        let up_padded_count = up_width.padded_body_bytes(n_up);
        let up_data_count = up_width.bytes_per_entry() * n_up;
        let mut up_body = vec![0u8; up_padded_count];
        reader.read_exact(&mut up_body)?;
        crc_digest.update(&up_body);
        // Decode only the actual data bytes (skip the 0-2 byte tail pad).
        let up_vec: Vec<u32> = match up_width {
            WeightWidth::U16 => decode_u16_to_u32_vec(&up_body[..up_data_count]),
            WeightWidth::U32 => up_body[..up_data_count]
                .chunks_exact(4)
                .map(|c| u32::from_le_bytes(c.try_into().unwrap()))
                .collect(),
        };

        // Read down weights body (padded).
        let down_padded_count = down_width.padded_body_bytes(n_down);
        let down_data_count = down_width.bytes_per_entry() * n_down;
        let mut down_body = vec![0u8; down_padded_count];
        reader.read_exact(&mut down_body)?;
        crc_digest.update(&down_body);
        let down_vec: Vec<u32> = match down_width {
            WeightWidth::U16 => decode_u16_to_u32_vec(&down_body[..down_data_count]),
            WeightWidth::U32 => down_body[..down_data_count]
                .chunks_exact(4)
                .map(|c| u32::from_le_bytes(c.try_into().unwrap()))
                .collect(),
        };

        let no_middle_len = HEADER_LEN + up_padded_count + down_padded_count + FOOTER_LEN;
        let with_middle_len = no_middle_len + 4 * (n_up + n_down);

        let (up_middle, down_middle): (Vec<u32>, Vec<u32>) = match file_len {
            len if len == no_middle_len => (Vec::new(), Vec::new()),
            len if len == with_middle_len => {
                let mut up_middle = Vec::with_capacity(n_up);
                for _ in 0..n_up {
                    let mut buf = [0u8; 4];
                    reader.read_exact(&mut buf)?;
                    crc_digest.update(&buf);
                    up_middle.push(u32::from_le_bytes(buf));
                }
                let mut down_middle = Vec::with_capacity(n_down);
                for _ in 0..n_down {
                    let mut buf = [0u8; 4];
                    reader.read_exact(&mut buf)?;
                    crc_digest.update(&buf);
                    down_middle.push(u32::from_le_bytes(buf));
                }
                (up_middle, down_middle)
            }
            len => anyhow::bail!(
                "Invalid cch.weights size: got {}, expected {} (no middles) or {} (with middles)",
                len,
                no_middle_len,
                with_middle_len
            ),
        };

        let computed_crc = crc_digest.finalize();
        let mut footer = [0u8; FOOTER_LEN];
        reader.read_exact(&mut footer)?;
        let stored_crc = u64::from_le_bytes(footer[0..8].try_into().unwrap());
        anyhow::ensure!(
            computed_crc == stored_crc,
            "CRC64 mismatch in cch.weights: computed 0x{:016X}, stored 0x{:016X}",
            computed_crc,
            stored_crc
        );

        Ok(CchWeights {
            up: WeightArray::from_vec_u32(up_vec),
            down: WeightArray::from_vec_u32(down_vec),
            up_middle: ArcCow::from_vec(up_middle),
            down_middle: ArcCow::from_vec(down_middle),
        })
    }
}

/// Decode a u16-compact body into a `Vec<u32>`, mapping the
/// `u16::MAX` sentinel back to `u32::MAX`.
#[inline]
fn decode_u16_to_u32_vec(bytes: &[u8]) -> Vec<u32> {
    bytes
        .chunks_exact(2)
        .map(|c| {
            let v = u16::from_le_bytes(c.try_into().unwrap());
            if v == u16::MAX { u32::MAX } else { v as u32 }
        })
        .collect()
}

/// Parsed cch.weights header.
#[derive(Debug, Clone, Copy)]
pub(crate) struct CchWeightsHeader {
    pub n_up: usize,
    pub n_down: usize,
    pub up_width: WeightWidth,
    pub down_width: WeightWidth,
}

/// Parse the 32-byte CCH weights header.
///
/// v3 (#306 PR 2): header byte 7 carries `width_flags`:
///   bit 0 → up body is u16  (else u32)
///   bit 1 → down body is u16 (else u32)
///
/// v2 readers wrote 0 in byte 7, so a v2-as-v3 read sees
/// `up_width = down_width = U32` — exactly the v2 semantic.
/// Shared by the owned, zero-copy, and mmap-backed readers.
fn parse_header(header: &[u8]) -> Result<CchWeightsHeader> {
    anyhow::ensure!(
        header.len() >= HEADER_LEN,
        "cch.weights header too short: {} bytes",
        header.len()
    );
    let magic = u32::from_le_bytes(header[0..4].try_into().unwrap());
    anyhow::ensure!(
        magic == MAGIC,
        "Invalid magic: expected 0x{:08X}, got 0x{:08X}",
        MAGIC,
        magic
    );
    let version = u16::from_le_bytes(header[4..6].try_into().unwrap());
    anyhow::ensure!(
        version == VERSION || version == VERSION_V2,
        "Unsupported cch.weights version {} (expected {} or {}). \
         v1 stored deciseconds/millimeters; re-run step 8 to regenerate \
         as v2/v3 (seconds/meters, #297/#306).",
        version,
        VERSION,
        VERSION_V2,
    );
    let width_flags = if version == VERSION { header[7] } else { 0 };
    let up_width = if width_flags & UP_COMPACT_FLAG != 0 {
        WeightWidth::U16
    } else {
        WeightWidth::U32
    };
    let down_width = if width_flags & DOWN_COMPACT_FLAG != 0 {
        WeightWidth::U16
    } else {
        WeightWidth::U32
    };
    let n_up = u64::from_le_bytes(header[8..16].try_into().unwrap()) as usize;
    let n_down = u64::from_le_bytes(header[16..24].try_into().unwrap()) as usize;
    Ok(CchWeightsHeader {
        n_up,
        n_down,
        up_width,
        down_width,
    })
}
