//! CCH weights format - customized edge weights for CCH
//!
//! Stores per-mode edge weights for both UP and DOWN edges.
//! Generated by Step 8 (customization).

use anyhow::Result;
use std::fs::File;
use std::io::{BufReader, Read};
use std::path::Path;

use super::crc;

const MAGIC: u32 = 0x43434857; // "CCHW"

/// CCH weights - stores weights and relaxed middle nodes for UP and DOWN edges.
/// The middle arrays are the post-triangle-relaxation middles — these are the
/// correct middles for path unpacking (the topology's middles are from contraction
/// and may be suboptimal).
#[derive(Debug, Clone)]
pub struct CchWeights {
    pub up: Vec<u32>,
    pub down: Vec<u32>,
    /// Relaxed middle nodes for UP shortcuts (empty if not available — use topo middles)
    pub up_middle: Vec<u32>,
    /// Relaxed middle nodes for DOWN shortcuts (empty if not available — use topo middles)
    pub down_middle: Vec<u32>,
}

pub struct CchWeightsFile;

impl CchWeightsFile {
    pub fn read<P: AsRef<Path>>(path: P) -> Result<CchWeights> {
        let file = File::open(path.as_ref())?;
        let file_len = file.metadata()?.len() as usize;
        let mut reader = BufReader::new(file);
        let mut crc_digest = crc::Digest::new();

        // Read header (32 bytes)
        // magic(4) + reserved(4) + n_up(8) + n_down(8) + reserved(8) = 32
        let mut header = [0u8; 32];
        reader.read_exact(&mut header)?;
        crc_digest.update(&header);

        let magic = u32::from_le_bytes([header[0], header[1], header[2], header[3]]);
        if magic != MAGIC {
            anyhow::bail!(
                "Invalid magic: expected 0x{:08X}, got 0x{:08X}",
                MAGIC,
                magic
            );
        }

        let n_up = u64::from_le_bytes([
            header[8], header[9], header[10], header[11], header[12], header[13], header[14],
            header[15],
        ]) as usize;
        let n_down = u64::from_le_bytes([
            header[16], header[17], header[18], header[19], header[20], header[21], header[22],
            header[23],
        ]) as usize;

        // Read up weights
        let mut up = Vec::with_capacity(n_up);
        for _ in 0..n_up {
            let mut buf = [0u8; 4];
            reader.read_exact(&mut buf)?;
            crc_digest.update(&buf);
            up.push(u32::from_le_bytes(buf));
        }

        // Read down weights
        let mut down = Vec::with_capacity(n_down);
        for _ in 0..n_down {
            let mut buf = [0u8; 4];
            reader.read_exact(&mut buf)?;
            crc_digest.update(&buf);
            down.push(u32::from_le_bytes(buf));
        }

        let expected_v1_len = 32 + 4 * (n_up + n_down) + 16;
        let expected_v2_len = expected_v1_len + 4 * (n_up + n_down);

        let (up_middle, down_middle) = match file_len {
            len if len == expected_v1_len => (Vec::new(), Vec::new()),
            len if len == expected_v2_len => {
                // Read relaxed middle arrays (v2: after weights, before CRC)
                let mut up_middle = Vec::with_capacity(n_up);
                for _ in 0..n_up {
                    let mut buf = [0u8; 4];
                    reader.read_exact(&mut buf)?;
                    crc_digest.update(&buf);
                    up_middle.push(u32::from_le_bytes(buf));
                }
                let mut down_middle = Vec::with_capacity(n_down);
                for _ in 0..n_down {
                    let mut buf = [0u8; 4];
                    reader.read_exact(&mut buf)?;
                    crc_digest.update(&buf);
                    down_middle.push(u32::from_le_bytes(buf));
                }
                (up_middle, down_middle)
            }
            len => anyhow::bail!(
                "Invalid cch.weights size for {}: got {}, expected {} (v1) or {} (v2)",
                path.as_ref().display(),
                len,
                expected_v1_len,
                expected_v2_len
            ),
        };

        // Verify CRC64
        let computed_crc = crc_digest.finalize();
        let mut footer = [0u8; 16];
        reader.read_exact(&mut footer)?;
        let stored_crc = u64::from_le_bytes(footer[0..8].try_into().unwrap());
        anyhow::ensure!(
            computed_crc == stored_crc,
            "CRC64 mismatch in cch.weights: computed 0x{:016X}, stored 0x{:016X}",
            computed_crc,
            stored_crc
        );

        Ok(CchWeights {
            up,
            down,
            up_middle,
            down_middle,
        })
    }
}
