//! CCH weights format - customized edge weights for CCH
//!
//! Stores per-mode edge weights for both UP and DOWN edges.
//! Generated by Step 8 (customization).
//!
//! # Zero-Copy Reads (#147, #296)
//!
//! For Belgium-scale data, four modes × {time, dist} weights total
//! ~6 GB on disk. Eagerly copying these into `Vec<u32>` doubles the
//! resident memory of an mmap-backed server (mmap pages + Vec heap).
//! The fields are `ArcCow<u32>` so they can hold either an owned
//! `Vec<u32>` (legacy / writer / construction sites) or a zero-copy
//! view into a memory-mapped container section, with the `Arc<Mmap>`
//! clone keeping the mapping live for the lifetime of the struct.
//!
//! # Eviction interaction (#149 / #296)
//!
//! After boot, the server hints `madvise(MADV_DONTNEED)` on the
//! `cch_weights.up`/`.down` byte ranges because the routing hot path
//! reads through pre-built flat adjacencies, not these arrays. The
//! `ArcCow::Mmap` variant holds the same `Arc<Mmap>` that owns the
//! pages — dropping a `CchWeights` decrements that strong count, and
//! once all clones drop, `munmap` runs and the kernel reclaims the
//! pages. The madvise hint stays valid until then; subsequent rare
//! reads (validators, transit fingerprint hash, recustomizers) page
//! the bytes back in at standard fault cost.

use anyhow::Result;
use std::fs::File;
use std::io::{BufReader, Read};
use std::path::Path;
use std::sync::Arc;

use super::crc;
use super::mmap::ArcCow;

const MAGIC: u32 = 0x43434857; // "CCHW"
const HEADER_LEN: usize = 32;
const FOOTER_LEN: usize = 16;
/// Current on-disk version. v2 stores body in seconds (time weights)
/// or meters (distance weights). v1 stored deciseconds / millimeters
/// and is rejected — re-run step 8 to regenerate.
const VERSION: u16 = 2;

/// CCH weights - stores weights and relaxed middle nodes for UP and DOWN edges.
/// The middle arrays are the post-triangle-relaxation middles — these are the
/// correct middles for path unpacking (the topology's middles are from contraction
/// and may be suboptimal).
///
/// Fields are [`ArcCow<u32>`] so they can either own a `Vec<u32>`
/// (legacy / writer / construction sites) or hold an `Arc<Mmap>`-backed
/// zero-copy view over a section of a `*.butterfly` container (#296).
/// All `&self.up` access patterns deref to `&[u32]` regardless of variant.
#[derive(Debug, Clone)]
pub struct CchWeights {
    pub up: ArcCow<u32>,
    pub down: ArcCow<u32>,
    /// Relaxed middle nodes for UP shortcuts (empty if not available — use topo middles)
    pub up_middle: ArcCow<u32>,
    /// Relaxed middle nodes for DOWN shortcuts (empty if not available — use topo middles)
    pub down_middle: ArcCow<u32>,
}

pub struct CchWeightsFile;

impl CchWeightsFile {
    pub fn read<P: AsRef<Path>>(path: P) -> Result<CchWeights> {
        let file = File::open(path.as_ref())?;
        let file_len = file.metadata()?.len() as usize;
        Self::read_from_reader(BufReader::new(file), file_len)
    }

    /// Read directly from an in-memory byte slice (e.g. an mmap-backed
    /// section of a `butterfly.dat` container). Allocating path —
    /// produces owning `ArcCow::Owned` Vecs.
    pub fn read_from_bytes(bytes: &[u8]) -> Result<CchWeights> {
        Self::read_from_reader(std::io::Cursor::new(bytes), bytes.len())
    }

    /// Legacy zero-copy reader retained for tests / tools that already
    /// hold a `'static [u8]` (typically leaked `Box<[u8]>` fixtures).
    /// Production now wires through [`Self::read_from_mmap_unverified`]
    /// instead so the `Arc<Mmap>` strong count actually drops when the
    /// `CchWeights` goes out of scope (#296). This reader copies the
    /// body into owned `Vec<u32>` slabs — there is no `&'static` view
    /// stored in the returned struct.
    ///
    /// CRC is verified before returning.
    pub fn read_from_bytes_zero_copy(bytes: &'static [u8]) -> Result<CchWeights> {
        Self::read_from_bytes_zero_copy_inner(bytes, true)
    }

    /// Same as [`Self::read_from_bytes_zero_copy`] but elides the
    /// internal CRC walk over the body bytes. Caller MUST guarantee
    /// the bytes have already been verified upstream (e.g. via
    /// [`crate::formats::lazy_verify::LazyContainer`]). Skipping the
    /// per-format CRC here avoids paging the body in twice on the
    /// container load path.
    pub fn read_from_bytes_zero_copy_unverified(bytes: &'static [u8]) -> Result<CchWeights> {
        Self::read_from_bytes_zero_copy_inner(bytes, false)
    }

    /// Production mmap-backed reader (#296). Each `ArcCow<u32>` sub-field
    /// holds a clone of the `Arc<Mmap>` covering this container, so when
    /// the returned `CchWeights` drops, every Arc clone drops with it.
    /// Once the strong count reaches 0, `Mmap::drop` calls `munmap` and
    /// the kernel reclaims the pages (the madvise(DONTNEED) hint applied
    /// at boot stays valid for the mapping's lifetime).
    ///
    /// `byte_offset` and `byte_len` describe the position and length of
    /// the section within the container, as recorded in the directory
    /// entry. CRC walking is the caller's responsibility (typically
    /// driven through the lazy CRC layer before this call).
    ///
    /// The container writer guarantees 8-byte section alignment; combined
    /// with the 32-byte header, the four u32 sub-arrays start at offsets
    /// that are 4-byte aligned, matching `align_of::<u32>() == 4`.
    pub fn read_from_mmap_unverified(
        mmap: Arc<memmap2::Mmap>,
        byte_offset: usize,
        byte_len: usize,
    ) -> Result<CchWeights> {
        anyhow::ensure!(
            byte_offset.saturating_add(byte_len) <= mmap.len(),
            "cch.weights section out of bounds: off={byte_offset} len={byte_len} mmap_len={}",
            mmap.len()
        );
        anyhow::ensure!(
            byte_len >= HEADER_LEN + FOOTER_LEN,
            "cch.weights section too short for header+footer: {byte_len} bytes",
        );

        let header = &mmap[byte_offset..byte_offset + HEADER_LEN];
        let (n_up, n_down) = parse_header(header)?;

        // Layout: header(32) | up(4*n_up) | down(4*n_down) |
        //         [v2: up_middle(4*n_up) | down_middle(4*n_down)] |
        //         footer(16)
        let up_bytes = 4usize
            .checked_mul(n_up)
            .ok_or_else(|| anyhow::anyhow!("cch.weights up byte len overflow for n_up={n_up}"))?;
        let down_bytes = 4usize.checked_mul(n_down).ok_or_else(|| {
            anyhow::anyhow!("cch.weights down byte len overflow for n_down={n_down}")
        })?;
        let body_v1 = up_bytes
            .checked_add(down_bytes)
            .ok_or_else(|| anyhow::anyhow!("cch.weights body size overflow"))?;
        let expected_v1_len = HEADER_LEN
            .checked_add(body_v1)
            .and_then(|n| n.checked_add(FOOTER_LEN))
            .ok_or_else(|| anyhow::anyhow!("cch.weights section size overflow"))?;
        let expected_v2_len = expected_v1_len
            .checked_add(body_v1)
            .ok_or_else(|| anyhow::anyhow!("cch.weights v2 section size overflow"))?;
        let is_v2 = match byte_len {
            n if n == expected_v1_len => false,
            n if n == expected_v2_len => true,
            n => anyhow::bail!(
                "Invalid cch.weights size: got {}, expected {} (v1) or {} (v2)",
                n,
                expected_v1_len,
                expected_v2_len
            ),
        };

        // Container-absolute byte offsets for each sub-array.
        let up_off = byte_offset + HEADER_LEN;
        let down_off = up_off + up_bytes;

        let up = ArcCow::<u32>::from_mmap(Arc::clone(&mmap), up_off, n_up)?;
        let down = ArcCow::<u32>::from_mmap(Arc::clone(&mmap), down_off, n_down)?;

        let (up_middle, down_middle) = if is_v2 {
            let upm_off = down_off + down_bytes;
            let dnm_off = upm_off + up_bytes;
            let upm = ArcCow::<u32>::from_mmap(Arc::clone(&mmap), upm_off, n_up)?;
            // Final clone consumes the local `mmap` binding.
            let dnm = ArcCow::<u32>::from_mmap(mmap, dnm_off, n_down)?;
            (upm, dnm)
        } else {
            // Empty arrays — no need to drag the mmap along; empty
            // `Vec<u32>` doesn't allocate.
            let _ = mmap; // suppress unused-binding warning on v1
            (ArcCow::from_vec(Vec::new()), ArcCow::from_vec(Vec::new()))
        };

        Ok(CchWeights {
            up,
            down,
            up_middle,
            down_middle,
        })
    }

    fn read_from_bytes_zero_copy_inner(bytes: &'static [u8], verify: bool) -> Result<CchWeights> {
        // ----- Header (32 bytes) -----
        anyhow::ensure!(
            bytes.len() >= HEADER_LEN + FOOTER_LEN,
            "cch.weights too short for header+footer: {} bytes",
            bytes.len()
        );
        // Container guarantees 8-byte section alignment, but `bytemuck::cast_slice`
        // panics on misalignment. Validate explicitly so a misuse from tests/tools
        // returns a typed error instead of aborting the process.
        anyhow::ensure!(
            (bytes.as_ptr() as usize).is_multiple_of(4),
            "cch.weights section must start 4-byte aligned (got addr 0x{:x})",
            bytes.as_ptr() as usize
        );
        let header = &bytes[..HEADER_LEN];
        let (n_up, n_down) = parse_header(header)?;

        // ----- Layout: header(32) | up(4*n_up) | down(4*n_down) |
        //               [v2: up_middle(4*n_up) | down_middle(4*n_down)] |
        //               footer(16)
        let expected_v1_len = HEADER_LEN + 4 * (n_up + n_down) + FOOTER_LEN;
        let expected_v2_len = expected_v1_len + 4 * (n_up + n_down);
        let is_v2 = match bytes.len() {
            n if n == expected_v1_len => false,
            n if n == expected_v2_len => true,
            n => anyhow::bail!(
                "Invalid cch.weights size: got {}, expected {} (v1) or {} (v2)",
                n,
                expected_v1_len,
                expected_v2_len
            ),
        };

        let up_off = HEADER_LEN;
        let up_end = up_off + 4 * n_up;
        let down_off = up_end;
        let down_end = down_off + 4 * n_down;

        let up_slice: &[u32] = bytemuck::cast_slice(&bytes[up_off..up_end]);
        let down_slice: &[u32] = bytemuck::cast_slice(&bytes[down_off..down_end]);

        let (up_middle, down_middle, body_end) = if is_v2 {
            let upm_off = down_end;
            let upm_end = upm_off + 4 * n_up;
            let dnm_off = upm_end;
            let dnm_end = dnm_off + 4 * n_down;
            let upm: &[u32] = bytemuck::cast_slice(&bytes[upm_off..upm_end]);
            let dnm: &[u32] = bytemuck::cast_slice(&bytes[dnm_off..dnm_end]);
            (upm.to_vec(), dnm.to_vec(), dnm_end)
        } else {
            (Vec::new(), Vec::new(), down_end)
        };

        // ----- CRC: covers everything before the 16-byte footer -----
        if verify {
            let body = &bytes[..body_end];
            let computed_crc = {
                let mut d = crc::Digest::new();
                d.update(body);
                d.finalize()
            };
            let footer = &bytes[body_end..body_end + FOOTER_LEN];
            let stored_crc = u64::from_le_bytes(footer[0..8].try_into().unwrap());
            anyhow::ensure!(
                computed_crc == stored_crc,
                "CRC64 mismatch in cch.weights: computed 0x{:016X}, stored 0x{:016X}",
                computed_crc,
                stored_crc
            );
        }

        // Legacy `'static` zero-copy path now copies into `Vec<u32>` —
        // production load goes through [`Self::read_from_mmap_unverified`].
        // The few remaining test fixtures that leak buffers don't care
        // about the extra Vec; they're tiny by construction.
        Ok(CchWeights {
            up: ArcCow::from_vec(up_slice.to_vec()),
            down: ArcCow::from_vec(down_slice.to_vec()),
            up_middle: ArcCow::from_vec(up_middle),
            down_middle: ArcCow::from_vec(down_middle),
        })
    }

    fn read_from_reader<R: Read>(mut reader: R, file_len: usize) -> Result<CchWeights> {
        let mut crc_digest = crc::Digest::new();

        // Read header (32 bytes)
        // magic(4) + reserved(4) + n_up(8) + n_down(8) + reserved(8) = 32
        let mut header = [0u8; HEADER_LEN];
        reader.read_exact(&mut header)?;
        crc_digest.update(&header);

        let magic = u32::from_le_bytes([header[0], header[1], header[2], header[3]]);
        if magic != MAGIC {
            anyhow::bail!(
                "Invalid magic: expected 0x{:08X}, got 0x{:08X}",
                MAGIC,
                magic
            );
        }

        let version = u16::from_le_bytes([header[4], header[5]]);
        anyhow::ensure!(
            version == VERSION,
            "Unsupported cch.weights version {} (expected {}). \
             v1 stored deciseconds/millimeters; re-run step 8 to regenerate as v2 (seconds/meters, #297).",
            version,
            VERSION,
        );

        let n_up = u64::from_le_bytes([
            header[8], header[9], header[10], header[11], header[12], header[13], header[14],
            header[15],
        ]) as usize;
        let n_down = u64::from_le_bytes([
            header[16], header[17], header[18], header[19], header[20], header[21], header[22],
            header[23],
        ]) as usize;

        // Read up weights
        let mut up = Vec::with_capacity(n_up);
        for _ in 0..n_up {
            let mut buf = [0u8; 4];
            reader.read_exact(&mut buf)?;
            crc_digest.update(&buf);
            up.push(u32::from_le_bytes(buf));
        }

        // Read down weights
        let mut down = Vec::with_capacity(n_down);
        for _ in 0..n_down {
            let mut buf = [0u8; 4];
            reader.read_exact(&mut buf)?;
            crc_digest.update(&buf);
            down.push(u32::from_le_bytes(buf));
        }

        let expected_v1_len = HEADER_LEN + 4 * (n_up + n_down) + FOOTER_LEN;
        let expected_v2_len = expected_v1_len + 4 * (n_up + n_down);

        let (up_middle, down_middle): (Vec<u32>, Vec<u32>) = match file_len {
            len if len == expected_v1_len => (Vec::new(), Vec::new()),
            len if len == expected_v2_len => {
                // Read relaxed middle arrays (v2: after weights, before CRC)
                let mut up_middle = Vec::with_capacity(n_up);
                for _ in 0..n_up {
                    let mut buf = [0u8; 4];
                    reader.read_exact(&mut buf)?;
                    crc_digest.update(&buf);
                    up_middle.push(u32::from_le_bytes(buf));
                }
                let mut down_middle = Vec::with_capacity(n_down);
                for _ in 0..n_down {
                    let mut buf = [0u8; 4];
                    reader.read_exact(&mut buf)?;
                    crc_digest.update(&buf);
                    down_middle.push(u32::from_le_bytes(buf));
                }
                (up_middle, down_middle)
            }
            len => anyhow::bail!(
                "Invalid cch.weights size: got {}, expected {} (v1) or {} (v2)",
                len,
                expected_v1_len,
                expected_v2_len
            ),
        };

        // Verify CRC64
        let computed_crc = crc_digest.finalize();
        let mut footer = [0u8; FOOTER_LEN];
        reader.read_exact(&mut footer)?;
        let stored_crc = u64::from_le_bytes(footer[0..8].try_into().unwrap());
        anyhow::ensure!(
            computed_crc == stored_crc,
            "CRC64 mismatch in cch.weights: computed 0x{:016X}, stored 0x{:016X}",
            computed_crc,
            stored_crc
        );

        Ok(CchWeights {
            up: ArcCow::from_vec(up),
            down: ArcCow::from_vec(down),
            up_middle: ArcCow::from_vec(up_middle),
            down_middle: ArcCow::from_vec(down_middle),
        })
    }
}

/// Parse the 32-byte CCH weights header and return `(n_up, n_down)`.
/// Shared by the owned, zero-copy, and mmap-backed readers.
fn parse_header(header: &[u8]) -> Result<(usize, usize)> {
    anyhow::ensure!(
        header.len() >= HEADER_LEN,
        "cch.weights header too short: {} bytes",
        header.len()
    );
    let magic = u32::from_le_bytes(header[0..4].try_into().unwrap());
    anyhow::ensure!(
        magic == MAGIC,
        "Invalid magic: expected 0x{:08X}, got 0x{:08X}",
        MAGIC,
        magic
    );
    // #297: enforce v2 (seconds/meters). v1 (deciseconds/millimeters)
    // is rejected — re-run step 8 to regenerate.
    let version = u16::from_le_bytes(header[4..6].try_into().unwrap());
    anyhow::ensure!(
        version == VERSION,
        "Unsupported cch.weights version {} (expected {}). \
         v1 stored deciseconds/millimeters; re-run step 8 to regenerate as v2 (seconds/meters, #297).",
        version,
        VERSION,
    );
    let n_up = u64::from_le_bytes(header[8..16].try_into().unwrap()) as usize;
    let n_down = u64::from_le_bytes(header[16..24].try_into().unwrap()) as usize;
    Ok((n_up, n_down))
}
