#!/usr/bin/env bash
# Emit geocode/data/shards/MANIFEST.toml documenting every built shard.
#
# Reads each *.bfgs in geocode/data/shards/ and extracts:
#   - iso2:           BFGS v5 header bytes 6..8 (ASCII)
#   - record_count:   BFGS v5 header bytes 8..12 (LE u32)
#   - file_size_mb:   stat -c%s
#   - sha256:         sha256sum
#   - source:         best-effort lookup from `dl/regions/<region>.toml`
#                     `[[address]]` `id` field (concatenated when multi-region)
set -euo pipefail
cd "$(dirname "$0")/.."
out=geocode/data/shards/MANIFEST.toml

# Map ISO2 -> source label (mirrors scripts/build_country_shards.sh).
declare -A SOURCES=(
    [LU]='OpenAddresses oa-lu-countrywide (job 823471)'
    [AT]='OpenAddresses oa-at-countrywide (job 824498)'
    [CH]='OpenAddresses oa-ch-countrywide (job 824053)'
    [FR]='OpenAddresses oa-fr-countrywide (job 743120)'
    [NL]='OpenAddresses oa-nl-countrywide (job 823433)'
    [AU]='OpenAddresses oa-au-countrywide (job 824415)'
    [ES]='OpenAddresses oa-es-countrywide (job 823991)'
    [BE]='OpenAddresses oa-be-{bru,vlg,wal}-{fr,nl,de} (6 regional feeds, jobs 824406/8/9/10/12/13)'
    [DE]='OpenAddresses oa-de-{14 states} BB,BW,HB,HE,HH,MV,NI,NW,RP,SH,SL,SN,ST,TH'
    [JP]='OpenAddresses oa-jp-{8 prefectures} Aichi,Chiba,Fukuoka,Gifu,Hyogo,Ibaraki,Saitama,Shizuoka'
    [US]='OpenAddresses oa-us-{9 states} AZ,DC,DE,IN,NC,NJ,NY,RI,TX'
    [BR]='OpenAddresses oa-br-{8 states} CE,MG,PE,PR,RJ,RS,SC,SP'
    [IN]='Geofabrik OSM PBF india.pbf addr:* tags (no OpenAddresses feed)'
    [GB]='Geofabrik OSM PBF great-britain.pbf addr:* tags (no OpenAddresses feed)'
    [IT]='Geofabrik OSM PBF italy.pbf addr:* tags (no OpenAddresses feed)'
)

date_utc=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

{
    echo "# butterfly-geocode shard manifest"
    echo "# Generated by scripts/build_manifest.sh on $date_utc"
    echo "# Format: BFGS v5 (geocode/src/shard/mod.rs::VERSION)"
    echo ""
    echo "[meta]"
    echo "version = 5"
    echo "generated = \"$date_utc\""
    echo ""
}
total_records=0
total_bytes=0
shard_count=0
for f in geocode/data/shards/*.bfgs; do
    [ -f "$f" ] || continue
    iso2=$(python3 -c "
import sys
with open('$f', 'rb') as fh:
    h = fh.read(12)
print(h[6:8].decode('ascii'))
")
    rec=$(python3 -c "
import struct
with open('$f', 'rb') as fh:
    h = fh.read(12)
print(struct.unpack('<I', h[8:12])[0])
")
    size=$(stat -c%s "$f")
    size_mb=$(awk "BEGIN{printf \"%.1f\", $size/1048576}")
    sha=$(sha256sum "$f" | awk '{print $1}')
    src="${SOURCES[$iso2]:-unknown}"

    {
        echo "[[shard]]"
        echo "iso2 = \"$iso2\""
        echo "path = \"$f\""
        echo "record_count = $rec"
        echo "file_size_bytes = $size"
        echo "file_size_mb = $size_mb"
        echo "sha256 = \"$sha\""
        echo "source = \"\"\"$src\"\"\""
        echo ""
    }
    total_records=$((total_records + rec))
    total_bytes=$((total_bytes + size))
    shard_count=$((shard_count + 1))
done > /tmp/manifest_shards.toml

{
    cat /tmp/manifest_shards.toml
    echo ""
    echo "[totals]"
    echo "shard_count = $shard_count"
    echo "total_records = $total_records"
    echo "total_bytes = $total_bytes"
    total_mb=$(awk "BEGIN{printf \"%.1f\", $total_bytes/1048576}")
    echo "total_size_mb = $total_mb"
} > "$out.tmp"

# Prepend the meta block (already written above, but we redirected
# stdout — redo cleanly).
{
    echo "# butterfly-geocode shard manifest"
    echo "# Generated by scripts/build_manifest.sh on $date_utc"
    echo "# Format: BFGS v5 (geocode/src/shard/mod.rs::VERSION)"
    echo ""
    echo "[meta]"
    echo "version = 5"
    echo "generated = \"$date_utc\""
    echo "shard_count = $shard_count"
    echo "total_records = $total_records"
    echo ""
    cat /tmp/manifest_shards.toml
} > "$out"
rm -f /tmp/manifest_shards.toml "$out.tmp"
echo "wrote $out ($shard_count shards, $total_records records)"
