// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `osmformat.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:OSMPBF.HeaderBlock)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct HeaderBlock {
    // message fields
    // @@protoc_insertion_point(field:OSMPBF.HeaderBlock.writingprogram)
    pub writingprogram: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:OSMPBF.HeaderBlock.source)
    pub source: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:OSMPBF.HeaderBlock.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a HeaderBlock {
    fn default() -> &'a HeaderBlock {
        <HeaderBlock as ::protobuf::Message>::default_instance()
    }
}

impl HeaderBlock {
    pub fn new() -> HeaderBlock {
        ::std::default::Default::default()
    }

    // optional string writingprogram = 16;

    pub fn writingprogram(&self) -> &str {
        match self.writingprogram.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_writingprogram(&mut self) {
        self.writingprogram = ::std::option::Option::None;
    }

    pub fn has_writingprogram(&self) -> bool {
        self.writingprogram.is_some()
    }

    // Param is passed by value, moved
    pub fn set_writingprogram(&mut self, v: ::std::string::String) {
        self.writingprogram = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_writingprogram(&mut self) -> &mut ::std::string::String {
        if self.writingprogram.is_none() {
            self.writingprogram = ::std::option::Option::Some(::std::string::String::new());
        }
        self.writingprogram.as_mut().unwrap()
    }

    // Take field
    pub fn take_writingprogram(&mut self) -> ::std::string::String {
        self.writingprogram.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string source = 17;

    pub fn source(&self) -> &str {
        match self.source.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_source(&mut self) {
        self.source = ::std::option::Option::None;
    }

    pub fn has_source(&self) -> bool {
        self.source.is_some()
    }

    // Param is passed by value, moved
    pub fn set_source(&mut self, v: ::std::string::String) {
        self.source = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_source(&mut self) -> &mut ::std::string::String {
        if self.source.is_none() {
            self.source = ::std::option::Option::Some(::std::string::String::new());
        }
        self.source.as_mut().unwrap()
    }

    // Take field
    pub fn take_source(&mut self) -> ::std::string::String {
        self.source.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "writingprogram",
            |m: &HeaderBlock| { &m.writingprogram },
            |m: &mut HeaderBlock| { &mut m.writingprogram },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "source",
            |m: &HeaderBlock| { &m.source },
            |m: &mut HeaderBlock| { &mut m.source },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<HeaderBlock>(
            "HeaderBlock",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for HeaderBlock {
    const NAME: &'static str = "HeaderBlock";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                130 => {
                    self.writingprogram = ::std::option::Option::Some(is.read_string()?);
                },
                138 => {
                    self.source = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.writingprogram.as_ref() {
            my_size += ::protobuf::rt::string_size(16, &v);
        }
        if let Some(v) = self.source.as_ref() {
            my_size += ::protobuf::rt::string_size(17, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.writingprogram.as_ref() {
            os.write_string(16, v)?;
        }
        if let Some(v) = self.source.as_ref() {
            os.write_string(17, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> HeaderBlock {
        HeaderBlock::new()
    }

    fn clear(&mut self) {
        self.writingprogram = ::std::option::Option::None;
        self.source = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static HeaderBlock {
        static instance: HeaderBlock = HeaderBlock {
            writingprogram: ::std::option::Option::None,
            source: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for HeaderBlock {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("HeaderBlock").unwrap()).clone()
    }
}

impl ::std::fmt::Display for HeaderBlock {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HeaderBlock {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:OSMPBF.PrimitiveBlock)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PrimitiveBlock {
    // message fields
    // @@protoc_insertion_point(field:OSMPBF.PrimitiveBlock.stringtable)
    pub stringtable: ::protobuf::MessageField<StringTable>,
    // @@protoc_insertion_point(field:OSMPBF.PrimitiveBlock.primitivegroup)
    pub primitivegroup: ::std::vec::Vec<PrimitiveGroup>,
    // @@protoc_insertion_point(field:OSMPBF.PrimitiveBlock.granularity)
    pub granularity: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:OSMPBF.PrimitiveBlock.lat_offset)
    pub lat_offset: ::std::option::Option<i64>,
    // @@protoc_insertion_point(field:OSMPBF.PrimitiveBlock.lon_offset)
    pub lon_offset: ::std::option::Option<i64>,
    // @@protoc_insertion_point(field:OSMPBF.PrimitiveBlock.date_granularity)
    pub date_granularity: ::std::option::Option<i32>,
    // special fields
    // @@protoc_insertion_point(special_field:OSMPBF.PrimitiveBlock.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PrimitiveBlock {
    fn default() -> &'a PrimitiveBlock {
        <PrimitiveBlock as ::protobuf::Message>::default_instance()
    }
}

impl PrimitiveBlock {
    pub fn new() -> PrimitiveBlock {
        ::std::default::Default::default()
    }

    // optional int32 granularity = 17;

    pub fn granularity(&self) -> i32 {
        self.granularity.unwrap_or(100i32)
    }

    pub fn clear_granularity(&mut self) {
        self.granularity = ::std::option::Option::None;
    }

    pub fn has_granularity(&self) -> bool {
        self.granularity.is_some()
    }

    // Param is passed by value, moved
    pub fn set_granularity(&mut self, v: i32) {
        self.granularity = ::std::option::Option::Some(v);
    }

    // optional int64 lat_offset = 19;

    pub fn lat_offset(&self) -> i64 {
        self.lat_offset.unwrap_or(0i64)
    }

    pub fn clear_lat_offset(&mut self) {
        self.lat_offset = ::std::option::Option::None;
    }

    pub fn has_lat_offset(&self) -> bool {
        self.lat_offset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_lat_offset(&mut self, v: i64) {
        self.lat_offset = ::std::option::Option::Some(v);
    }

    // optional int64 lon_offset = 20;

    pub fn lon_offset(&self) -> i64 {
        self.lon_offset.unwrap_or(0i64)
    }

    pub fn clear_lon_offset(&mut self) {
        self.lon_offset = ::std::option::Option::None;
    }

    pub fn has_lon_offset(&self) -> bool {
        self.lon_offset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_lon_offset(&mut self, v: i64) {
        self.lon_offset = ::std::option::Option::Some(v);
    }

    // optional int32 date_granularity = 18;

    pub fn date_granularity(&self) -> i32 {
        self.date_granularity.unwrap_or(1000i32)
    }

    pub fn clear_date_granularity(&mut self) {
        self.date_granularity = ::std::option::Option::None;
    }

    pub fn has_date_granularity(&self) -> bool {
        self.date_granularity.is_some()
    }

    // Param is passed by value, moved
    pub fn set_date_granularity(&mut self, v: i32) {
        self.date_granularity = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, StringTable>(
            "stringtable",
            |m: &PrimitiveBlock| { &m.stringtable },
            |m: &mut PrimitiveBlock| { &mut m.stringtable },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "primitivegroup",
            |m: &PrimitiveBlock| { &m.primitivegroup },
            |m: &mut PrimitiveBlock| { &mut m.primitivegroup },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "granularity",
            |m: &PrimitiveBlock| { &m.granularity },
            |m: &mut PrimitiveBlock| { &mut m.granularity },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "lat_offset",
            |m: &PrimitiveBlock| { &m.lat_offset },
            |m: &mut PrimitiveBlock| { &mut m.lat_offset },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "lon_offset",
            |m: &PrimitiveBlock| { &m.lon_offset },
            |m: &mut PrimitiveBlock| { &mut m.lon_offset },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "date_granularity",
            |m: &PrimitiveBlock| { &m.date_granularity },
            |m: &mut PrimitiveBlock| { &mut m.date_granularity },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PrimitiveBlock>(
            "PrimitiveBlock",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PrimitiveBlock {
    const NAME: &'static str = "PrimitiveBlock";

    fn is_initialized(&self) -> bool {
        if self.stringtable.is_none() {
            return false;
        }
        for v in &self.stringtable {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.primitivegroup {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.stringtable)?;
                },
                18 => {
                    self.primitivegroup.push(is.read_message()?);
                },
                136 => {
                    self.granularity = ::std::option::Option::Some(is.read_int32()?);
                },
                152 => {
                    self.lat_offset = ::std::option::Option::Some(is.read_int64()?);
                },
                160 => {
                    self.lon_offset = ::std::option::Option::Some(is.read_int64()?);
                },
                144 => {
                    self.date_granularity = ::std::option::Option::Some(is.read_int32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.stringtable.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.primitivegroup {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.granularity {
            my_size += ::protobuf::rt::int32_size(17, v);
        }
        if let Some(v) = self.lat_offset {
            my_size += ::protobuf::rt::int64_size(19, v);
        }
        if let Some(v) = self.lon_offset {
            my_size += ::protobuf::rt::int64_size(20, v);
        }
        if let Some(v) = self.date_granularity {
            my_size += ::protobuf::rt::int32_size(18, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.stringtable.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        for v in &self.primitivegroup {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if let Some(v) = self.granularity {
            os.write_int32(17, v)?;
        }
        if let Some(v) = self.lat_offset {
            os.write_int64(19, v)?;
        }
        if let Some(v) = self.lon_offset {
            os.write_int64(20, v)?;
        }
        if let Some(v) = self.date_granularity {
            os.write_int32(18, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PrimitiveBlock {
        PrimitiveBlock::new()
    }

    fn clear(&mut self) {
        self.stringtable.clear();
        self.primitivegroup.clear();
        self.granularity = ::std::option::Option::None;
        self.lat_offset = ::std::option::Option::None;
        self.lon_offset = ::std::option::Option::None;
        self.date_granularity = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PrimitiveBlock {
        static instance: PrimitiveBlock = PrimitiveBlock {
            stringtable: ::protobuf::MessageField::none(),
            primitivegroup: ::std::vec::Vec::new(),
            granularity: ::std::option::Option::None,
            lat_offset: ::std::option::Option::None,
            lon_offset: ::std::option::Option::None,
            date_granularity: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PrimitiveBlock {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PrimitiveBlock").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PrimitiveBlock {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PrimitiveBlock {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:OSMPBF.PrimitiveGroup)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PrimitiveGroup {
    // message fields
    // @@protoc_insertion_point(field:OSMPBF.PrimitiveGroup.nodes)
    pub nodes: ::std::vec::Vec<Node>,
    // @@protoc_insertion_point(field:OSMPBF.PrimitiveGroup.dense)
    pub dense: ::protobuf::MessageField<DenseNodes>,
    // @@protoc_insertion_point(field:OSMPBF.PrimitiveGroup.ways)
    pub ways: ::std::vec::Vec<Way>,
    // @@protoc_insertion_point(field:OSMPBF.PrimitiveGroup.relations)
    pub relations: ::std::vec::Vec<Relation>,
    // special fields
    // @@protoc_insertion_point(special_field:OSMPBF.PrimitiveGroup.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PrimitiveGroup {
    fn default() -> &'a PrimitiveGroup {
        <PrimitiveGroup as ::protobuf::Message>::default_instance()
    }
}

impl PrimitiveGroup {
    pub fn new() -> PrimitiveGroup {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "nodes",
            |m: &PrimitiveGroup| { &m.nodes },
            |m: &mut PrimitiveGroup| { &mut m.nodes },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, DenseNodes>(
            "dense",
            |m: &PrimitiveGroup| { &m.dense },
            |m: &mut PrimitiveGroup| { &mut m.dense },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "ways",
            |m: &PrimitiveGroup| { &m.ways },
            |m: &mut PrimitiveGroup| { &mut m.ways },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "relations",
            |m: &PrimitiveGroup| { &m.relations },
            |m: &mut PrimitiveGroup| { &mut m.relations },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PrimitiveGroup>(
            "PrimitiveGroup",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PrimitiveGroup {
    const NAME: &'static str = "PrimitiveGroup";

    fn is_initialized(&self) -> bool {
        for v in &self.nodes {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.dense {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.ways {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.relations {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.nodes.push(is.read_message()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.dense)?;
                },
                26 => {
                    self.ways.push(is.read_message()?);
                },
                34 => {
                    self.relations.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.nodes {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.dense.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.ways {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.relations {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.nodes {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        if let Some(v) = self.dense.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        for v in &self.ways {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        for v in &self.relations {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PrimitiveGroup {
        PrimitiveGroup::new()
    }

    fn clear(&mut self) {
        self.nodes.clear();
        self.dense.clear();
        self.ways.clear();
        self.relations.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PrimitiveGroup {
        static instance: PrimitiveGroup = PrimitiveGroup {
            nodes: ::std::vec::Vec::new(),
            dense: ::protobuf::MessageField::none(),
            ways: ::std::vec::Vec::new(),
            relations: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PrimitiveGroup {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PrimitiveGroup").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PrimitiveGroup {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PrimitiveGroup {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:OSMPBF.StringTable)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct StringTable {
    // message fields
    // @@protoc_insertion_point(field:OSMPBF.StringTable.s)
    pub s: ::std::vec::Vec<::std::vec::Vec<u8>>,
    // special fields
    // @@protoc_insertion_point(special_field:OSMPBF.StringTable.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a StringTable {
    fn default() -> &'a StringTable {
        <StringTable as ::protobuf::Message>::default_instance()
    }
}

impl StringTable {
    pub fn new() -> StringTable {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "s",
            |m: &StringTable| { &m.s },
            |m: &mut StringTable| { &mut m.s },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<StringTable>(
            "StringTable",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for StringTable {
    const NAME: &'static str = "StringTable";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.s.push(is.read_bytes()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.s {
            my_size += ::protobuf::rt::bytes_size(1, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.s {
            os.write_bytes(1, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> StringTable {
        StringTable::new()
    }

    fn clear(&mut self) {
        self.s.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static StringTable {
        static instance: StringTable = StringTable {
            s: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for StringTable {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("StringTable").unwrap()).clone()
    }
}

impl ::std::fmt::Display for StringTable {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for StringTable {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:OSMPBF.Node)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Node {
    // message fields
    // @@protoc_insertion_point(field:OSMPBF.Node.id)
    pub id: ::std::option::Option<i64>,
    // @@protoc_insertion_point(field:OSMPBF.Node.keys)
    pub keys: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:OSMPBF.Node.vals)
    pub vals: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:OSMPBF.Node.lat)
    pub lat: ::std::option::Option<i64>,
    // @@protoc_insertion_point(field:OSMPBF.Node.lon)
    pub lon: ::std::option::Option<i64>,
    // special fields
    // @@protoc_insertion_point(special_field:OSMPBF.Node.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Node {
    fn default() -> &'a Node {
        <Node as ::protobuf::Message>::default_instance()
    }
}

impl Node {
    pub fn new() -> Node {
        ::std::default::Default::default()
    }

    // required sint64 id = 1;

    pub fn id(&self) -> i64 {
        self.id.unwrap_or(0)
    }

    pub fn clear_id(&mut self) {
        self.id = ::std::option::Option::None;
    }

    pub fn has_id(&self) -> bool {
        self.id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: i64) {
        self.id = ::std::option::Option::Some(v);
    }

    // required sint64 lat = 8;

    pub fn lat(&self) -> i64 {
        self.lat.unwrap_or(0)
    }

    pub fn clear_lat(&mut self) {
        self.lat = ::std::option::Option::None;
    }

    pub fn has_lat(&self) -> bool {
        self.lat.is_some()
    }

    // Param is passed by value, moved
    pub fn set_lat(&mut self, v: i64) {
        self.lat = ::std::option::Option::Some(v);
    }

    // required sint64 lon = 9;

    pub fn lon(&self) -> i64 {
        self.lon.unwrap_or(0)
    }

    pub fn clear_lon(&mut self) {
        self.lon = ::std::option::Option::None;
    }

    pub fn has_lon(&self) -> bool {
        self.lon.is_some()
    }

    // Param is passed by value, moved
    pub fn set_lon(&mut self, v: i64) {
        self.lon = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "id",
            |m: &Node| { &m.id },
            |m: &mut Node| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "keys",
            |m: &Node| { &m.keys },
            |m: &mut Node| { &mut m.keys },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "vals",
            |m: &Node| { &m.vals },
            |m: &mut Node| { &mut m.vals },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "lat",
            |m: &Node| { &m.lat },
            |m: &mut Node| { &mut m.lat },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "lon",
            |m: &Node| { &m.lon },
            |m: &mut Node| { &mut m.lon },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Node>(
            "Node",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Node {
    const NAME: &'static str = "Node";

    fn is_initialized(&self) -> bool {
        if self.id.is_none() {
            return false;
        }
        if self.lat.is_none() {
            return false;
        }
        if self.lon.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = ::std::option::Option::Some(is.read_sint64()?);
                },
                18 => {
                    is.read_repeated_packed_uint32_into(&mut self.keys)?;
                },
                16 => {
                    self.keys.push(is.read_uint32()?);
                },
                26 => {
                    is.read_repeated_packed_uint32_into(&mut self.vals)?;
                },
                24 => {
                    self.vals.push(is.read_uint32()?);
                },
                64 => {
                    self.lat = ::std::option::Option::Some(is.read_sint64()?);
                },
                72 => {
                    self.lon = ::std::option::Option::Some(is.read_sint64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id {
            my_size += ::protobuf::rt::sint64_size(1, v);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(2, &self.keys);
        my_size += ::protobuf::rt::vec_packed_uint32_size(3, &self.vals);
        if let Some(v) = self.lat {
            my_size += ::protobuf::rt::sint64_size(8, v);
        }
        if let Some(v) = self.lon {
            my_size += ::protobuf::rt::sint64_size(9, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id {
            os.write_sint64(1, v)?;
        }
        os.write_repeated_packed_uint32(2, &self.keys)?;
        os.write_repeated_packed_uint32(3, &self.vals)?;
        if let Some(v) = self.lat {
            os.write_sint64(8, v)?;
        }
        if let Some(v) = self.lon {
            os.write_sint64(9, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Node {
        Node::new()
    }

    fn clear(&mut self) {
        self.id = ::std::option::Option::None;
        self.keys.clear();
        self.vals.clear();
        self.lat = ::std::option::Option::None;
        self.lon = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Node {
        static instance: Node = Node {
            id: ::std::option::Option::None,
            keys: ::std::vec::Vec::new(),
            vals: ::std::vec::Vec::new(),
            lat: ::std::option::Option::None,
            lon: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Node {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Node").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Node {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Node {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:OSMPBF.DenseNodes)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DenseNodes {
    // message fields
    // @@protoc_insertion_point(field:OSMPBF.DenseNodes.id)
    pub id: ::std::vec::Vec<i64>,
    // @@protoc_insertion_point(field:OSMPBF.DenseNodes.lat)
    pub lat: ::std::vec::Vec<i64>,
    // @@protoc_insertion_point(field:OSMPBF.DenseNodes.lon)
    pub lon: ::std::vec::Vec<i64>,
    // @@protoc_insertion_point(field:OSMPBF.DenseNodes.keys_vals)
    pub keys_vals: ::std::vec::Vec<i32>,
    // special fields
    // @@protoc_insertion_point(special_field:OSMPBF.DenseNodes.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DenseNodes {
    fn default() -> &'a DenseNodes {
        <DenseNodes as ::protobuf::Message>::default_instance()
    }
}

impl DenseNodes {
    pub fn new() -> DenseNodes {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "id",
            |m: &DenseNodes| { &m.id },
            |m: &mut DenseNodes| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "lat",
            |m: &DenseNodes| { &m.lat },
            |m: &mut DenseNodes| { &mut m.lat },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "lon",
            |m: &DenseNodes| { &m.lon },
            |m: &mut DenseNodes| { &mut m.lon },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "keys_vals",
            |m: &DenseNodes| { &m.keys_vals },
            |m: &mut DenseNodes| { &mut m.keys_vals },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DenseNodes>(
            "DenseNodes",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DenseNodes {
    const NAME: &'static str = "DenseNodes";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    is.read_repeated_packed_sint64_into(&mut self.id)?;
                },
                8 => {
                    self.id.push(is.read_sint64()?);
                },
                66 => {
                    is.read_repeated_packed_sint64_into(&mut self.lat)?;
                },
                64 => {
                    self.lat.push(is.read_sint64()?);
                },
                74 => {
                    is.read_repeated_packed_sint64_into(&mut self.lon)?;
                },
                72 => {
                    self.lon.push(is.read_sint64()?);
                },
                82 => {
                    is.read_repeated_packed_int32_into(&mut self.keys_vals)?;
                },
                80 => {
                    self.keys_vals.push(is.read_int32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::vec_packed_sint64_size(1, &self.id);
        my_size += ::protobuf::rt::vec_packed_sint64_size(8, &self.lat);
        my_size += ::protobuf::rt::vec_packed_sint64_size(9, &self.lon);
        my_size += ::protobuf::rt::vec_packed_int32_size(10, &self.keys_vals);
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_repeated_packed_sint64(1, &self.id)?;
        os.write_repeated_packed_sint64(8, &self.lat)?;
        os.write_repeated_packed_sint64(9, &self.lon)?;
        os.write_repeated_packed_int32(10, &self.keys_vals)?;
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DenseNodes {
        DenseNodes::new()
    }

    fn clear(&mut self) {
        self.id.clear();
        self.lat.clear();
        self.lon.clear();
        self.keys_vals.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DenseNodes {
        static instance: DenseNodes = DenseNodes {
            id: ::std::vec::Vec::new(),
            lat: ::std::vec::Vec::new(),
            lon: ::std::vec::Vec::new(),
            keys_vals: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DenseNodes {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DenseNodes").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DenseNodes {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DenseNodes {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:OSMPBF.Way)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Way {
    // message fields
    // @@protoc_insertion_point(field:OSMPBF.Way.id)
    pub id: ::std::option::Option<i64>,
    // @@protoc_insertion_point(field:OSMPBF.Way.keys)
    pub keys: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:OSMPBF.Way.vals)
    pub vals: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:OSMPBF.Way.refs)
    pub refs: ::std::vec::Vec<i64>,
    // special fields
    // @@protoc_insertion_point(special_field:OSMPBF.Way.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Way {
    fn default() -> &'a Way {
        <Way as ::protobuf::Message>::default_instance()
    }
}

impl Way {
    pub fn new() -> Way {
        ::std::default::Default::default()
    }

    // required int64 id = 1;

    pub fn id(&self) -> i64 {
        self.id.unwrap_or(0)
    }

    pub fn clear_id(&mut self) {
        self.id = ::std::option::Option::None;
    }

    pub fn has_id(&self) -> bool {
        self.id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: i64) {
        self.id = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "id",
            |m: &Way| { &m.id },
            |m: &mut Way| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "keys",
            |m: &Way| { &m.keys },
            |m: &mut Way| { &mut m.keys },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "vals",
            |m: &Way| { &m.vals },
            |m: &mut Way| { &mut m.vals },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "refs",
            |m: &Way| { &m.refs },
            |m: &mut Way| { &mut m.refs },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Way>(
            "Way",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Way {
    const NAME: &'static str = "Way";

    fn is_initialized(&self) -> bool {
        if self.id.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = ::std::option::Option::Some(is.read_int64()?);
                },
                18 => {
                    is.read_repeated_packed_uint32_into(&mut self.keys)?;
                },
                16 => {
                    self.keys.push(is.read_uint32()?);
                },
                26 => {
                    is.read_repeated_packed_uint32_into(&mut self.vals)?;
                },
                24 => {
                    self.vals.push(is.read_uint32()?);
                },
                66 => {
                    is.read_repeated_packed_sint64_into(&mut self.refs)?;
                },
                64 => {
                    self.refs.push(is.read_sint64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id {
            my_size += ::protobuf::rt::int64_size(1, v);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(2, &self.keys);
        my_size += ::protobuf::rt::vec_packed_uint32_size(3, &self.vals);
        my_size += ::protobuf::rt::vec_packed_sint64_size(8, &self.refs);
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id {
            os.write_int64(1, v)?;
        }
        os.write_repeated_packed_uint32(2, &self.keys)?;
        os.write_repeated_packed_uint32(3, &self.vals)?;
        os.write_repeated_packed_sint64(8, &self.refs)?;
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Way {
        Way::new()
    }

    fn clear(&mut self) {
        self.id = ::std::option::Option::None;
        self.keys.clear();
        self.vals.clear();
        self.refs.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Way {
        static instance: Way = Way {
            id: ::std::option::Option::None,
            keys: ::std::vec::Vec::new(),
            vals: ::std::vec::Vec::new(),
            refs: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Way {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Way").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Way {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Way {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:OSMPBF.Relation)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Relation {
    // message fields
    // @@protoc_insertion_point(field:OSMPBF.Relation.id)
    pub id: ::std::option::Option<i64>,
    // @@protoc_insertion_point(field:OSMPBF.Relation.keys)
    pub keys: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:OSMPBF.Relation.vals)
    pub vals: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:OSMPBF.Relation.roles_sid)
    pub roles_sid: ::std::vec::Vec<i32>,
    // @@protoc_insertion_point(field:OSMPBF.Relation.memids)
    pub memids: ::std::vec::Vec<i64>,
    // @@protoc_insertion_point(field:OSMPBF.Relation.types)
    pub types: ::std::vec::Vec<::protobuf::EnumOrUnknown<relation::MemberType>>,
    // special fields
    // @@protoc_insertion_point(special_field:OSMPBF.Relation.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Relation {
    fn default() -> &'a Relation {
        <Relation as ::protobuf::Message>::default_instance()
    }
}

impl Relation {
    pub fn new() -> Relation {
        ::std::default::Default::default()
    }

    // required int64 id = 1;

    pub fn id(&self) -> i64 {
        self.id.unwrap_or(0)
    }

    pub fn clear_id(&mut self) {
        self.id = ::std::option::Option::None;
    }

    pub fn has_id(&self) -> bool {
        self.id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: i64) {
        self.id = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "id",
            |m: &Relation| { &m.id },
            |m: &mut Relation| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "keys",
            |m: &Relation| { &m.keys },
            |m: &mut Relation| { &mut m.keys },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "vals",
            |m: &Relation| { &m.vals },
            |m: &mut Relation| { &mut m.vals },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "roles_sid",
            |m: &Relation| { &m.roles_sid },
            |m: &mut Relation| { &mut m.roles_sid },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "memids",
            |m: &Relation| { &m.memids },
            |m: &mut Relation| { &mut m.memids },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "types",
            |m: &Relation| { &m.types },
            |m: &mut Relation| { &mut m.types },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Relation>(
            "Relation",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Relation {
    const NAME: &'static str = "Relation";

    fn is_initialized(&self) -> bool {
        if self.id.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = ::std::option::Option::Some(is.read_int64()?);
                },
                18 => {
                    is.read_repeated_packed_uint32_into(&mut self.keys)?;
                },
                16 => {
                    self.keys.push(is.read_uint32()?);
                },
                26 => {
                    is.read_repeated_packed_uint32_into(&mut self.vals)?;
                },
                24 => {
                    self.vals.push(is.read_uint32()?);
                },
                66 => {
                    is.read_repeated_packed_int32_into(&mut self.roles_sid)?;
                },
                64 => {
                    self.roles_sid.push(is.read_int32()?);
                },
                74 => {
                    is.read_repeated_packed_sint64_into(&mut self.memids)?;
                },
                72 => {
                    self.memids.push(is.read_sint64()?);
                },
                80 => {
                    self.types.push(is.read_enum_or_unknown()?);
                },
                82 => {
                    ::protobuf::rt::read_repeated_packed_enum_or_unknown_into(is, &mut self.types)?
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id {
            my_size += ::protobuf::rt::int64_size(1, v);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(2, &self.keys);
        my_size += ::protobuf::rt::vec_packed_uint32_size(3, &self.vals);
        my_size += ::protobuf::rt::vec_packed_int32_size(8, &self.roles_sid);
        my_size += ::protobuf::rt::vec_packed_sint64_size(9, &self.memids);
        my_size += ::protobuf::rt::vec_packed_enum_or_unknown_size(10, &self.types);
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id {
            os.write_int64(1, v)?;
        }
        os.write_repeated_packed_uint32(2, &self.keys)?;
        os.write_repeated_packed_uint32(3, &self.vals)?;
        os.write_repeated_packed_int32(8, &self.roles_sid)?;
        os.write_repeated_packed_sint64(9, &self.memids)?;
        os.write_repeated_packed_enum_or_unknown(10, &self.types)?;
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Relation {
        Relation::new()
    }

    fn clear(&mut self) {
        self.id = ::std::option::Option::None;
        self.keys.clear();
        self.vals.clear();
        self.roles_sid.clear();
        self.memids.clear();
        self.types.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Relation {
        static instance: Relation = Relation {
            id: ::std::option::Option::None,
            keys: ::std::vec::Vec::new(),
            vals: ::std::vec::Vec::new(),
            roles_sid: ::std::vec::Vec::new(),
            memids: ::std::vec::Vec::new(),
            types: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Relation {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Relation").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Relation {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Relation {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `Relation`
pub mod relation {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:OSMPBF.Relation.MemberType)
    pub enum MemberType {
        // @@protoc_insertion_point(enum_value:OSMPBF.Relation.MemberType.NODE)
        NODE = 0,
        // @@protoc_insertion_point(enum_value:OSMPBF.Relation.MemberType.WAY)
        WAY = 1,
        // @@protoc_insertion_point(enum_value:OSMPBF.Relation.MemberType.RELATION)
        RELATION = 2,
    }

    impl ::protobuf::Enum for MemberType {
        const NAME: &'static str = "MemberType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<MemberType> {
            match value {
                0 => ::std::option::Option::Some(MemberType::NODE),
                1 => ::std::option::Option::Some(MemberType::WAY),
                2 => ::std::option::Option::Some(MemberType::RELATION),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<MemberType> {
            match str {
                "NODE" => ::std::option::Option::Some(MemberType::NODE),
                "WAY" => ::std::option::Option::Some(MemberType::WAY),
                "RELATION" => ::std::option::Option::Some(MemberType::RELATION),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [MemberType] = &[
            MemberType::NODE,
            MemberType::WAY,
            MemberType::RELATION,
        ];
    }

    impl ::protobuf::EnumFull for MemberType {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("Relation.MemberType").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for MemberType {
        fn default() -> Self {
            MemberType::NODE
        }
    }

    impl MemberType {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<MemberType>("Relation.MemberType")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0fosmformat.proto\x12\x06OSMPBF\"M\n\x0bHeaderBlock\x12&\n\x0ewritin\
    gprogram\x18\x10\x20\x01(\tR\x0ewritingprogram\x12\x16\n\x06source\x18\
    \x11\x20\x01(\tR\x06source\"\xab\x02\n\x0ePrimitiveBlock\x125\n\x0bstrin\
    gtable\x18\x01\x20\x02(\x0b2\x13.OSMPBF.StringTableR\x0bstringtable\x12>\
    \n\x0eprimitivegroup\x18\x02\x20\x03(\x0b2\x16.OSMPBF.PrimitiveGroupR\
    \x0eprimitivegroup\x12'\n\x0bgranularity\x18\x11\x20\x01(\x05:\x03100R\
    \x0bgranularityB\0\x12\"\n\nlat_offset\x18\x13\x20\x01(\x03:\x010R\tlatO\
    ffsetB\0\x12\"\n\nlon_offset\x18\x14\x20\x01(\x03:\x010R\tlonOffsetB\0\
    \x121\n\x10date_granularity\x18\x12\x20\x01(\x05:\x041000R\x0fdateGranul\
    arityB\0\"\xaf\x01\n\x0ePrimitiveGroup\x12\"\n\x05nodes\x18\x01\x20\x03(\
    \x0b2\x0c.OSMPBF.NodeR\x05nodes\x12(\n\x05dense\x18\x02\x20\x01(\x0b2\
    \x12.OSMPBF.DenseNodesR\x05dense\x12\x1f\n\x04ways\x18\x03\x20\x03(\x0b2\
    \x0b.OSMPBF.WayR\x04ways\x12.\n\trelations\x18\x04\x20\x03(\x0b2\x10.OSM\
    PBF.RelationR\trelations\"\x1b\n\x0bStringTable\x12\x0c\n\x01s\x18\x01\
    \x20\x03(\x0cR\x01s\"j\n\x04Node\x12\x0e\n\x02id\x18\x01\x20\x02(\x12R\
    \x02id\x12\x16\n\x04keys\x18\x02\x20\x03(\rR\x04keysB\x02\x10\x01\x12\
    \x16\n\x04vals\x18\x03\x20\x03(\rR\x04valsB\x02\x10\x01\x12\x10\n\x03lat\
    \x18\x08\x20\x02(\x12R\x03lat\x12\x10\n\x03lon\x18\t\x20\x02(\x12R\x03lo\
    n\"m\n\nDenseNodes\x12\x12\n\x02id\x18\x01\x20\x03(\x12R\x02idB\x02\x10\
    \x01\x12\x14\n\x03lat\x18\x08\x20\x03(\x12R\x03latB\x02\x10\x01\x12\x14\
    \n\x03lon\x18\t\x20\x03(\x12R\x03lonB\x02\x10\x01\x12\x1f\n\tkeys_vals\
    \x18\n\x20\x03(\x05R\x08keysValsB\x02\x10\x01\"]\n\x03Way\x12\x0e\n\x02i\
    d\x18\x01\x20\x02(\x03R\x02id\x12\x16\n\x04keys\x18\x02\x20\x03(\rR\x04k\
    eysB\x02\x10\x01\x12\x16\n\x04vals\x18\x03\x20\x03(\rR\x04valsB\x02\x10\
    \x01\x12\x16\n\x04refs\x18\x08\x20\x03(\x12R\x04refsB\x02\x10\x01\"\xed\
    \x01\n\x08Relation\x12\x0e\n\x02id\x18\x01\x20\x02(\x03R\x02id\x12\x16\n\
    \x04keys\x18\x02\x20\x03(\rR\x04keysB\x02\x10\x01\x12\x16\n\x04vals\x18\
    \x03\x20\x03(\rR\x04valsB\x02\x10\x01\x12\x1f\n\troles_sid\x18\x08\x20\
    \x03(\x05R\x08rolesSidB\x02\x10\x01\x12\x1a\n\x06memids\x18\t\x20\x03(\
    \x12R\x06memidsB\x02\x10\x01\x125\n\x05types\x18\n\x20\x03(\x0e2\x1b.OSM\
    PBF.Relation.MemberTypeR\x05typesB\x02\x10\x01\"-\n\nMemberType\x12\x08\
    \n\x04NODE\x10\0\x12\x07\n\x03WAY\x10\x01\x12\x0c\n\x08RELATION\x10\x02B\
    \x0f\n\rcrosby.binaryb\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(8);
            messages.push(HeaderBlock::generated_message_descriptor_data());
            messages.push(PrimitiveBlock::generated_message_descriptor_data());
            messages.push(PrimitiveGroup::generated_message_descriptor_data());
            messages.push(StringTable::generated_message_descriptor_data());
            messages.push(Node::generated_message_descriptor_data());
            messages.push(DenseNodes::generated_message_descriptor_data());
            messages.push(Way::generated_message_descriptor_data());
            messages.push(Relation::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(relation::MemberType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
